name: Build and publish
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  github-release:
    name: Github release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
    - uses: softprops/action-gh-release@v2
      with:
        body_path: "RELEASE.md"
        tag_name: ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
