name: Build and publish
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  github-release:
    name: Github release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: pdm-project/setup-pdm@v4
      with:
        cache: true
    - run: pdm install --no-default --dev
    - name: Create release notes
      run: pdm run cz changelog $(pdm run cz version --project) --dry-run > body.md
    - run: cat body.md
    - uses: softprops/action-gh-release@v2
      with:
        body_path: body.md
        tag_name: ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
